//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AudioVisualesDBEntities : DbContext
    {
        public AudioVisualesDBEntities()
            : base("name=AudioVisualesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Rentas> Rentas { get; set; }
        public virtual DbSet<TandasLabor> TandasLabor { get; set; }
        public virtual DbSet<Tecnologias_Conexion> Tecnologias_Conexion { get; set; }
        public virtual DbSet<TipoEquipos> TipoEquipos { get; set; }
        public virtual DbSet<TipoEstados> TipoEstados { get; set; }
        public virtual DbSet<TipoPersonas> TipoPersonas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<vwTipoEquipo> vwTipoEquipo { get; set; }
        public virtual DbSet<vwEmpleados> vwEmpleados { get; set; }
        public virtual DbSet<Modelos> Modelos { get; set; }
    }
}
