//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentas
    {
        public int NoPrestamo { get; set; }
        public int IdEmpleado { get; set; }
        public int IdEquipo { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public System.DateTime FechaDevolucion { get; set; }
        public string Comentario { get; set; }
        public int Estado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Equipos Equipos { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
