
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class vwEquipos
{

    public int Id { get; set; }

    public string Descripcion { get; set; }

    public int No_Serial { get; set; }

    public string Service_tag { get; set; }

    public string Tipo_de_equipo { get; set; }

    public string Estado { get; set; }

    public string Marca { get; set; }

    public string Tecnologia_de_conexion { get; set; }

    public string Modelo { get; set; }

}

}
