
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class vwRentas
{

    public int NoPrestamo { get; set; }

    public System.DateTime FechaPrestamo { get; set; }

    public System.DateTime FechaDevolucion { get; set; }

    public string Descripcion { get; set; }

    public int No_Serial { get; set; }

    public string Service_tag { get; set; }

    public string Nombre { get; set; }

    public string Cedula { get; set; }

    public int No_Carnet { get; set; }

    public string Nombre_Empleado { get; set; }

    public string Cedula_Empleado { get; set; }

    public System.DateTime FechaIng__Empleado { get; set; }

    public string Comentario_Rentas { get; set; }

}

}
